In [2]:
import numpy as np

In [3]:
a=np.array([[3,8,4],[9,3,5],[11,15,17],[19,31,8]])

In [4]:
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [5]:
b=np.array([[4,8,7],[3,1,5],[6,9,13]])

In [6]:
b

array([[ 4,  8,  7],
       [ 3,  1,  5],
       [ 6,  9, 13]])

In [8]:
b.shape

(3, 3)

In [9]:
a.shape

(4, 3)

In [6]:
c=np.array([[[4,41],[8,81],[7,71]],[[3,31],[1,11],[5,51]],[[6,61],[9,91],[13,131]]])
c.shape

(3, 3, 2)

In [11]:
a[0:5:1,2]

array([ 4,  5, 17,  8])

In [12]:
a[1,:]

array([9, 3, 5])

In [13]:
a[0:5:1,2].shape

(4,)

In [4]:
a

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [14]:
a[:,-1:]

array([[ 4],
       [ 5],
       [17],
       [ 8]])

In [16]:
a[:,:]

array([[ 3,  8,  4],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [7]:
c

array([[[  4,  41],
        [  8,  81],
        [  7,  71]],

       [[  3,  31],
        [  1,  11],
        [  5,  51]],

       [[  6,  61],
        [  9,  91],
        [ 13, 131]]])

In [17]:
c[1:,1:,:1]

array([[[ 1],
        [ 5]],

       [[ 9],
        [13]]])

In [18]:
c[1:,0:1,:]

array([[[ 3, 31]],

       [[ 6, 61]]])

In [19]:
x=[3,5,6]
x+5

TypeError: can only concatenate list (not "int") to list

In [20]:
a+5

array([[ 8, 13,  9],
       [14,  8, 10],
       [16, 20, 22],
       [24, 36, 13]])

In [24]:
a[0,0]=6
a[0]

array([6, 8, 4])

In [29]:
a[0,:]=[4,6,9]
a

array([[ 4,  6,  9],
       [ 9,  3,  5],
       [11, 15, 17],
       [19, 31,  8]])

In [37]:
a[:,1]=[66,33,155,311]
a

array([[  4,  66,   9],
       [  9,  33,   5],
       [ 11, 155,  17],
       [ 19, 311,   8]])

In [39]:
a[:2,1:]=[[606,90],[303,50]]
a

array([[  4, 606,  90],
       [  9, 303,  50],
       [ 11, 155,  17],
       [ 19, 311,   8]])

In [40]:
a[4,:]=[1,1,1]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [41]:
np.append(a,[[1,1,1]],axis=0) #zero to add row-wise

array([[  4, 606,  90],
       [  9, 303,  50],
       [ 11, 155,  17],
       [ 19, 311,   8],
       [  1,   1,   1]])

In [46]:
np.append(a,[[3],[3],[3],[3]],axis=1)

array([[  4, 606,  90,   3],
       [  9, 303,  50,   3],
       [ 11, 155,  17,   3],
       [ 19, 311,   8,   3]])

In [47]:
np.delete(a,1,0)

array([[  4, 606,  90],
       [ 11, 155,  17],
       [ 19, 311,   8]])

In [49]:
np.delete(a,0,axis=1)

array([[606,  90],
       [303,  50],
       [155,  17],
       [311,   8]])

In [50]:
np.delete(a,1,axis=0)

array([[  4, 606,  90],
       [ 11, 155,  17],
       [ 19, 311,   8]])

In [52]:
a.shape,a.size

((4, 3), 12)

In [53]:
a.reshape(6,2)

array([[  4, 606],
       [ 90,   9],
       [303,  50],
       [ 11, 155],
       [ 17,  19],
       [311,   8]])

In [54]:
a.dtype

dtype('int32')

In [57]:
a1=np.array([3,4.4,5])

In [58]:
a1.dtype

dtype('float64')

In [59]:
a1.astype('uint16')

array([3, 4, 5], dtype=uint16)

In [60]:
a1.astype(int)

array([3, 4, 5])

In [61]:
a.mean(axis=1)

array([233.33333333, 120.66666667,  61.        , 112.66666667])

In [63]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
np.linspace(1,11,6)

array([ 1.,  3.,  5.,  7.,  9., 11.])

In [65]:
np.random.randint(1,15,[3,4])

array([[14,  6,  4, 12],
       [ 3,  5, 13,  2],
       [ 5, 14, 14, 13]])

In [ ]:
#nutshell
#we create array
# 1. np.array()
# 2. np.ones()
# 3. np.zeros()
# 4. np.arange()
# 5. np.linespace()
# 5. np.random.randint()

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
np.arange(1,11,1)#create array acc. to desire variable

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.linspace(0,10,10,dtype=int)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10])

In [9]:
list(range(1,11,1))#always donr in int 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
np.random.seed(10)#for save the no. fixed the no.
np.random.randint(31,6000,[4,3])

array([[1320, 4654, 1375],
       [3472, 1211, 2040],
       [4860, 1551, 1980],
       [2073, 1063, 1128]])

In [15]:
np.random.rand(3,4)#create the no. less tah 0to1

array([[0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607],
       [0.72175532, 0.29187607, 0.91777412, 0.71457578]])

In [17]:
r=np.loadtxt('Somedata.txt',dtype=str)
r

array(['hi', 'this', 'is', 'a', 'text', 'file', 'for', 'some', 'data'],
      dtype='<U4')

In [19]:
r=np.loadtxt('moredata.txt',dtype=int)
r

array([[ 34,  77, 888],
       [ 98, 786, 544]])

In [20]:
p=np.random.rand(3,4)
p

array([[0.54254437, 0.14217005, 0.37334076, 0.67413362],
       [0.44183317, 0.43401399, 0.61776698, 0.51313824],
       [0.65039718, 0.60103895, 0.8052232 , 0.52164715]])

In [21]:
np.savetxt('new.txt',p,delimiter=" ")#save the file in folder and delimiter is create the space